name: FTP Deployment

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the 'main' branch

jobs:
  deploy:
    name: FTP Deploy Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # Checks out your repository's code

      - name: Install Dependencies
        run: npm install # Install dependencies

      - name: Build Project
        run: npm run build # Build the project (output is usually in 'build/')

      - name: FTP Deploy Forked
        uses: snorux/FTP-Deploy-Action@1.3.2
        with:
          server: ftpupload.net # FTP server address
          username: if0_37694479 # FTP username
          password: qLQphFCzJXW # Securely reference FTP password
          protocol: ftps # Use FTPS for security
          port: 21 # Default FTP port
          local-dir: ./build/ # Directory with built files
          server-dir: /htdocs/getUp_Assignment/ # Remote directory
          log-level: standard # Options: minimal, standard, verbose
          dry-run: false # Set to 'true' for testing
