name: FTP Deployment

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the 'main' branch

jobs:
  deploy:
    name: FTP Deploy Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Debug - List repository structure
      - name: List Repository Structure
        run: ls -la

      # Step 3: Install dependencies (if package.json exists)
      - name: Install Dependencies
        if: ${{ exists('package.json') }} # Run this step only if package.json exists
        run: npm install

      # Step 4: Build the project (if required, like for React or similar apps)
      - name: Build Project
        if: ${{ exists('package.json') }} # Run this step only if package.json exists
        run: npm run build
        working-directory: ./ # Change if package.json is in a subdirectory (e.g., ./frontend/)

      # Step 5: Debug - Verify build directory exists
      - name: Verify Build Directory
        run: ls -la ./build/ # Check that the build directory was created

      # Step 6: FTP Deploy
      - name: FTP Deploy Forked
        uses: snorux/FTP-Deploy-Action@1.3.2
        with:
          server: ftpupload.net # Replace with your FTP server address
          username: if0_37694479 # Replace with your FTP username
          password: qLQphFCzJXW # Use GitHub Secrets for security
          protocol: ftps # Use secure protocol
          port: 21 # Default FTP port
          local-dir: ./build/ # Path to the files you want to deploy
          server-dir: /htdocs/getUp_Assignment/ # Path on the FTP server
          state-name: deploy-state.json # Track file changes for efficient deployment
          log-level: standard # Options: minimal, standard, verbose
          dry-run: false # Set to true to test without deploying
          dangerous-clean-slate: false # Use with caution to clear server-dir before deployment
          exclude: |
            .git*
            node_modules/
            *.log
            *.md
          max-retries: 3 # Retry failed connections

