name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deploy Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Debug repository structure
      - name: List Repository Files
        run: ls -la

      # Step 3: Navigate to Project Directory (if applicable)
      - name: Navigate to Frontend Directory
        run: |
          if [ -d frontend ]; then
            echo "Navigating to 'frontend' directory."
            cd frontend
          else
            echo "'frontend' directory not found. Running from root."
          fi

      # Step 4: Check for package.json
      - name: Check for package.json
        run: |
          if [ -f package.json ]; then
            echo "package.json exists:"
            cat package.json
          else
            echo "package.json not found! Exiting..."
            exit 1
          fi

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 6: Build the project
      - name: Build Project
        run: npm run build

      # Step 7: Verify build directory
      - name: Verify Build Directory
        run: |
          if [ -d ./build ]; then
            echo "Build directory exists:"
            ls -la ./build
          else
            echo "Build directory not found! Exiting..."
            exit 1
          fi

      # Step 8: FTP Deploy
      - name: FTP Deploy Forked
        uses: snorux/FTP-Deploy-Action@1.3.2
        with:
          server: ftpupload.net
          username: if0_37694479
          password: qLQphFCzJXW
          protocol: ftps
          port: 21
          local-dir: ./build/
          server-dir: /htdocs/getUp_Assignment/
