name: FTP Deployment

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the 'main' branch

jobs:
  deploy:
    name: FTP Deploy Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Debug - List repository structure
      - name: List Repository Structure
        run: ls -la

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then
            echo "Installing dependencies..."
            npm install
          else
            echo "package.json not found, skipping npm install."
          fi

      # Step 4: Run Build Command
      - name: Build Project
        run: |
          if [ -f package.json ]; then
            echo "Building project..."
            npm run build || exit 1
          else
            echo "package.json not found, skipping build step."
          fi

      # Step 5: Inspect Build Output
      - name: Inspect Build Output
        run: |
          echo "Inspecting build output..."
          ls -la ./build || echo "Build directory not found."
          ls -la ./dist || echo "Dist directory not found."

      # Step 6: Verify Build Directory
      - name: Verify Build Directory
        run: |
          if [ -d ./build ]; then
            echo "Build directory exists:"
            ls -la ./build/
          elif [ -d ./dist ]; then
            echo "Dist directory exists:"
            ls -la ./dist/
          else
            echo "No valid build directory found. Please check your build step."
            exit 1
          fi

      # Step 7: FTP Deploy
      - name: FTP Deploy Forked
        uses: snorux/FTP-Deploy-Action@1.3.2
        with:
          server: ftpupload.net # Replace with your FTP server address
          username: if0_37694479 # Replace with your FTP username
          password: qLQphFCzJXW # Use GitHub Secrets for security
          protocol: ftps # Use secure protocol
          port: 21 # Default FTP port
          local-dir: ./build/ # Adjust if the directory is different (e.g., ./dist)
          server-dir: /htdocs/getUp_Assignment/ # Path on the FTP server
          state-name: deploy-state.json # Track file changes for efficient deployment
          log-level: standard # Options: minimal, standard, verbose
          dry-run: false # Set to true to test without deploying
          dangerous-clean-slate: false # Use with caution to clear server-dir before deployment
          exclude: |
            .git*
            node_modules/
            *.log
            *.md
          max-retries: 3 # Retry failed connections
